### ISSUE TITLE
基于Travis CI实现 Hexo 在 Github 和 Coding 的同步部署 - Payne's Blog

### ISSUE THREAD

**Issue by qinyuanpei** [qinyuanpei/qinyuanpei.github.io#6]
https://qinyuanpei.github.io/posts/1113828794/ 

 &emsp;&emsp;各位朋友，大家好，我是Payne，欢迎大家关注我的博客，我的博客地址是 https://qinyuanpei.github.io .在曾经的一篇博客：《持续集成在Hexo自动化部署上的实践》中，我为大家分享了在线持续集成服务  Travis CI 的相关内容，在这篇文章中我们通过  Travis CI 为 Hexo 提供了自动部署的支持。其原理是Github为 Travis

**Comment by aiokr** [comment]
在最后向coding提交的时候会警告
git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master
remote: Coding 提示: Authentication failed! 认证失败，请确认您输入了正确的账号密码
fatal: Authentication failed for 'https://aiokr:[secure]@git.coding.net/StarkChen/hitokoto.git/'
怎么办==

**Comment by qinyuanpei** [comment]
> @aiokr
> 在最后向coding提交的时候会警告
> git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master
> remote: Coding 提示: Authentication failed! 认证失败，请确认您输入了正确的账号密码
> fatal: Authentication failed for 'https://aiokr:[secure]@git.coding.net/StarkChen/hitokoto.git/'
> 怎么办==

这个非常明显呀，这个token是错误的，这个token由Coding生成，然后你需要把它添加到TravisCI后台的环境变量里，这样TravisCI才有权限给你的Coding仓库推送代码呀，你这个token怎么可能是secure呢？

**Comment by aiokr** [comment]
> @qinyuanpei
> > @aiokr
> > 在最后向coding提交的时候会警告
> > git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master
> > remote: Coding 提示: Authentication failed! 认证失败，请确认您输入了正确的账号密码
> > fatal: Authentication failed for 'https://aiokr:[secure]@git.coding.net/StarkChen/hitokoto.git/'
> > 怎么办==
> 
> 这个非常明显呀，这个token是错误的，这个token由Coding生成，然后你需要把它添加到TravisCI后台的环境变量里，这样TravisCI才有权限给你的Coding仓库推送代码呀，你这个token怎么可能是secure呢？

token 是secure 是因为填写token的时候关闭了value旁边的那个开关（按照截图做的）
我的token确实是在coding后台生成的，在电脑上实验也只能clone而不能push 权限都打开了

**Comment by qinyuanpei** [comment]
> @aiokr
> > @qinyuanpei
> > > @aiokr
> > > 在最后向coding提交的时候会警告
> > > git push --force --quiet "https://aiokr:${CO_TOKEN}@${CO_REF}" master:master
> > > remote: Coding 提示: Authentication failed! 认证失败，请确认您输入了正确的账号密码
> > > fatal: Authentication failed for 'https://aiokr:[secure]@git.coding.net/StarkChen/hitokoto.git/'
> > > 怎么办==
> > 
> > 这个非常明显呀，这个token是错误的，这个token由Coding生成，然后你需要把它添加到TravisCI后台的环境变量里，这样TravisCI才有权限给你的Coding仓库推送代码呀，你这个token怎么可能是secure呢？
> 
> token 是secure 是因为填写token的时候关闭了value旁边的那个开关（按照截图做的）
> 我的token确实是在coding后台生成的，在电脑上实验也只能clone而不能push 权限都打开了

我的建议有两点，第一，重新生成token，先在Git下测试能不能向仓库推送代码；第二，确认你的用户名，我注意到你前后的用户名不一致，前面是aiokr，而后面是StarkChen，我这个方法都稳定运行一个月了，应该不会有问题的呀！

**Comment by aiokr** [comment]
嗯 已经确认是用户名的问题了，重新注册了一个coding账号解决了，谢谢dalao。

**Comment by xkloveme** [comment]
> 嗯 已经确认是用户名的问题了，重新注册了一个coding账号解决了，谢谢dalao。

请问是用户名的什么问题?

**Comment by willin** [comment]
我也遇到了相同的diao问题 ，token 重新生成了也没用。

**Comment by qinyuanpei** [comment]
@willin，你注意下你用的是企业版还是个人版，去年有段时间它好像把个人版都升级到企业版了，因为被腾讯爸爸给收购了，而两个的地址是不大一样的。[https://blog.yuanpei.me](https://blog.yuanpei.me)

**Comment by willin** [comment]
对， 还加了个奇怪的 `令牌用户名`
