### ISSUE TITLE
请问可以出一个添加电影和读书功能的文章吗？

### ISSUE THREAD

**Issue by GeminiLight** [qinyuanpei/qinyuanpei.github.io#96]
被大佬博客的电影和书单功能吸引而来，但是个人能力有限没有复现出，希望有时间可以出篇相关的文章

**Comment by qinyuanpei** [comment]
你好，我并非什么大佬，关于这个电影和书单的功能，是使用一个Hexo的插件 [hexo-douban](https://github.com/mythsman/hexo-douban) 来实现的，我对这个插件进行了一点改造，以更加契合我目前使用的主题，请参考：[hexo-douban-plus](https://github.com/qinyuanpei/hexo-douban-plus)

**Comment by GeminiLight** [comment]
感谢
